### PR TITLE
build(deps): bump htslib from 1.16 to 1.19.1

### PR DESCRIPTION
**Pull request by sjackman**
Bump `htslib` from `1.16` to `1.19.1`

### CODE REVIEW

**Comment by pmarks** [comment]
@johanneskoester this helps clean up some dependency chains in our builds. (I don't currently have write access on this repo, otherwise I'd be happy to shepard this through).

**Comment by dlaehnemann** [comment]
Pinging Johannes via GitHub mentions only gets buried in tons conda-forge (and other) notifications, so he never sees those. So it's best to do that via some other channel. I just pinged him internally.

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
@pmarks, sorry, I thought you have that already. Just checked, you are in the "mergers" team, which should have the ability to merge PRs in all the repos here. Does that not work?

**Comment by pmarks** [comment]
Thanks for merging!  I didn't have the option to merge - perhaps because there was no approving review.  But I also didn't seem to be able to request a review, so maybe that was the issue.

**Pull request merged**
